dist: xenial
language: ruby
sudo: false

rvm:
  - 2.5.3
services:
  - mysql
env:
  - DB=mysql

before_script:
  - mysql -e 'create database myapp_test'
bundler_args: --binstubs=./bundler_stubs

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test rails test