dist: xenial
language: ruby
sudo: false

rvm:
  - 2.5.3
services:
  - mysql

before_install:
  - gem update --system
  - gem install bundler
  - rm -f ./config/database.yml
  - mv ./config/database.travis.yml ./config/database.yml
  - mysql -e 'CREATE DATABASE myapp_test;'

before_script:
  - rails db:migrate RAILS_ENV=test

script:
  - whenever --update-crontab
  - whenever -l
  - crontab -l